# Generated by Django 5.0.3 on 2024-04-19 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Offre'), (1, 'Demande')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('motdepasse', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alamy.poste')),
                ('intitule', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=100)),
                ('contactinfo', models.CharField(max_length=100)),
            ],
            bases=('alamy.poste',),
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alamy.poste')),
                ('localisation', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, null='true')),
                ('contactinfo', models.CharField(max_length=100)),
            ],
            bases=('alamy.poste',),
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alamy.poste')),
                ('texte', models.CharField(max_length=255)),
            ],
            bases=('alamy.poste',),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alamy.poste')),
                ('typeStg', models.IntegerField(choices=[(1, 'Ouvrier'), (2, 'Technicien'), (3, 'PFE')])),
                ('societe', models.CharField(max_length=100)),
                ('duree', models.IntegerField()),
                ('sujet', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            bases=('alamy.poste',),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alamy.poste')),
                ('depart', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('heuredep', models.TimeField()),
                ('contactinfo', models.CharField(max_length=100)),
            ],
            bases=('alamy.poste',),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('comment', models.TextField()),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alamy.poste')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alamy.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='poste',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alamy.utilisateur'),
        ),
        migrations.CreateModel(
            name='EvenementClub',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alamy.evenement')),
                ('club', models.CharField(max_length=100)),
            ],
            bases=('alamy.evenement',),
        ),
        migrations.CreateModel(
            name='EvenementSocial',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alamy.evenement')),
                ('prix', models.FloatField()),
                ('specialite', models.CharField(max_length=100)),
            ],
            bases=('alamy.evenement',),
        ),
    ]
