# Generated by Django 5.0.3 on 2024-04-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alamy', '0003_poste_comments_poste_comments_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poste',
            old_name='ikes_count',
            new_name='likes_count',
        ),
    ]
