# Generated by Django 5.0.3 on 2024-04-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alamy', '0004_rename_ikes_count_poste_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='dislike',
            field=models.BooleanField(null=True),
        ),
    ]
