# Generated by Django 5.0.3 on 2024-04-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alamy', '0005_reaction_dislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='utilisateur',
        ),
        migrations.AlterField(
            model_name='reaction',
            name='comment',
            field=models.TextField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='dislike',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='like',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
