# Generated by Django 5.0.3 on 2024-04-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alamy', '0007_remove_poste_comments_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='dislikes_count',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='poste',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poste',
            name='dislikes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poste',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
