# Generated by Django 5.0.3 on 2024-04-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alamy', '0008_remove_reaction_comments_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='comments',
        ),
    ]
