# Generated by Django 5.0.3 on 2024-04-28 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alamy', '0009_remove_poste_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alamy.utilisateur'),
        ),
    ]
