# Generated by Django 5.0.3 on 2024-05-05 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alamy', '0011_evenement_nombretickets_logement_nombretables_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='alamy.poste'),
        ),
    ]
