# Generated by Django 5.0.3 on 2024-05-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alamy', '0013_rename_nombre_personnes_reservation_nombre_tables4'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
