# Generated by Django 5.0.3 on 2024-05-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alamy', '0014_poste_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
