# Generated by Django 5.0.3 on 2024-05-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alamy', '0015_gamescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Morpion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grille', models.CharField(default='---------', max_length=9)),
                ('joueur_actif', models.CharField(default='X', max_length=1)),
            ],
        ),
    ]
