# Generated by Django 5.0.3 on 2024-05-18 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alamy', '0016_morpion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameScore',
        ),
        migrations.DeleteModel(
            name='Morpion',
        ),
    ]
